### 사용자 추가
POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "Test1"
}


### 잘못된 생성은 오류
POST http://localhost:8080/users
Content-Type: application/json

{
    "nick": "Test3"
}

### 사용자 목록보기
GET http://localhost:8080/users


### 잘못된 id 조회는 오류
GET http://localhost:8080/users/2393b10c-6eee-424e